"""empty message

Revision ID: a32a1ad2fe9b
Revises: a651e585ed88
Create Date: 2018-12-16 18:47:18.227757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32a1ad2fe9b'
down_revision = 'a651e585ed88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('date', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'date')
    # ### end Alembic commands ###
